function rdb = rdmLoad(basePath)

fid = fopen(fullfile(basePath, 'log.txt'), 'r') ;
text = fread(fid,+inf,'char=>char')' ;
fclose(fid) ;

tokens = regexp(text, '(\d+) spawn:(\d+) type:(\d+) \[([\d\w]+)\]', ...
  'tokens', 'dotexceptnewline') ;
rdb.basePath = basePath ;
rdb.objects.id = [] ;
rdb.objects.startTic = [] ;
rdb.objects.endTic = [];
rdb.objects.label = [] ;
rdb.player.tic = [] ;
rdb.player.position = [] ;
rdb.player.orientation = [] ;

for i = 1:numel(tokens)
  rdb.objects.id(i) = sscanf(tokens{i}{2},'%d') ;
  rdb.objects.startTic(i) = sscanf(tokens{i}{1},'%d') ;
  rdb.objects.endTic(i) = +inf ;
  rdb.objects.label(i) = sscanf(tokens{i}{3},'%d') ;
end

tokens = regexp(text, '(\d+) remove:(\d+)', 'tokens', 'dotexceptnewline') ;
for i = 1:numel(tokens)
  s = find(rdb.objects.id == sscanf(tokens{i}{2},'%d')) ;
  rdb.objects.endTic(s) = sscanf(tokens{i}{1},'%d') ;
end

names = dir(fullfile(basePath, 'rgb', '*.png')) ;
names = {names.name} ;
ids = regexp(names,'\d+', 'match') ;
for i = 1:numel(ids)
  rdb.ticks.id(i) = sscanf(ids{i}{1},'%d') ;
end

tokens = regexp(text, '(\d+) level loaded: ([\d\w]+)', 'tokens', 'dotexceptnewline') ;

for i = 1:numel(tokens)
  rdb.levels.name{i} = tokens{i}{2} ;
  rdb.levels.startTic(i) = sscanf(tokens{i}{1},'%d') ;
end
rdb.levels.endTic = [rdb.levels.startTic(2:end)-1, max(rdb.ticks.id)] ;

tokens = regexp(text, '(\d+) player:([\d-.,]+)', 'tokens', 'dotexceptnewline') ;
for i = 1:numel(tokens)
  rdb.player.tic(i) = sscanf(tokens{i}{1},'%d') ;
  xyza = sscanf(tokens{i}{2},'%f,%f,%f,%f') ;
  rdb.player.position(:,i) = xyza(1:3) ;
  rdb.player.orientation(i) = xyza(4) ;
end

rdb.classes.name = getNames() ;
rdb.classes.label = 0:numel(rdb.classes.name)-1 ;
end

function names = getNames()
names = {'PLAYER', ...
  'POSSESSED', ...
  'SHOTGUY', ...
  'VILE', ...
  'FIRE', ...
  'UNDEAD', ...
  'TRACER', ...
  'SMOKE', ...
  'FATSO', ...
  'FATSHOT', ...
  'CHAINGUY', ...
  'TROOP', ...
  'SERGEANT', ...
  'SHADOWS', ...
  'HEAD', ...
  'BRUISER', ...
  'BRUISERSHOT', ...
  'KNIGHT', ...
  'SKULL', ...
  'SPIDER', ...
  'BABY', ...
  'CYBORG', ...
  'PAIN', ...
  'WOLFSS', ...
  'KEEN', ...
  'BOSSBRAIN', ...
  'BOSSSPIT', ...
  'BOSSTARGET', ...
  'SPAWNSHOT', ...
  'SPAWNFIRE', ...
  'BARREL', ...
  'TROOPSHOT', ...
  'HEADSHOT', ...
  'ROCKET', ...
  'PLASMA', ...
  'BFG', ...
  'ARACHPLAZ', ...
  'PUFF', ...
  'BLOOD', ...
  'TFOG', ...
  'IFOG', ...
  'TELEPORTMAN', ...
  'EXTRABFG', ...
  'MISC0', ...
  'MISC1', ...
  'MISC2', ...
  'MISC3', ...
  'MISC4', ...
  'MISC5', ...
  'MISC6', ...
  'MISC7', ...
  'MISC8', ...
  'MISC9', ...
  'MISC10', ...
  'MISC11', ...
  'MISC12', ...
  'MISC13', ...
  'INS', ...
  'MISC14', ...
  'MISC15', ...
  'MISC16', ...
  'MEGA', ...
  'CLIP', ...
  'MISC17', ...
  'MISC18', ...
  'MISC19', ...
  'MISC20', ...
  'MISC21', ...
  'MISC22', ...
  'MISC23', ...
  'MISC24', ...
  'MISC25', ...
  'CHAINGUN', ...
  'MISC26', ...
  'MISC27', ...
  'MISC28', ...
  'SHOTGUN', ...
  'SUPERSHOTGUN', ...
  'MISC29', ...
  'MISC30', ...
  'MISC31', ...
  'MISC32', ...
  'MISC33', ...
  'MISC34', ...
  'MISC35', ...
  'MISC36', ...
  'MISC37', ...
  'MISC38', ...
  'MISC39', ...
  'MISC40', ...
  'MISC41', ...
  'MISC42', ...
  'MISC43', ...
  'MISC44', ...
  'MISC45', ...
  'MISC46', ...
  'MISC47', ...
  'MISC48', ...
  'MISC49', ...
  'MISC50', ...
  'MISC51', ...
  'MISC52', ...
  'MISC53', ...
  'MISC54', ...
  'MISC55', ...
  'MISC56', ...
  'MISC57', ...
  'MISC58', ...
  'MISC59', ...
  'MISC60', ...
  'MISC61', ...
  'MISC62', ...
  'MISC63', ...
  'MISC64', ...
  'MISC65', ...
  'MISC66', ...
  'MISC67', ...
  'MISC68', ...
  'MISC69', ...
  'MISC70', ...
  'MISC71', ...
  'MISC72', ...
  'MISC73', ...
  'MISC74', ...
  'MISC75', ...
  'MISC76', ...
  'MISC77', ...
  'MISC78', ...
  'MISC79', ...
  'MISC80', ...
  'MISC81', ...
  'MISC82', ...
  'MISC83', ...
  'MISC84', ...
  'MISC85', ...
  'MISC86'};
end