function rdb = rdmLoad(basePath)
%RDMLOAD   Load ResearchDoom database
%   RDB = RDMLOAD(BASEPATH) loads the ResearchDoom metadata given the
%   directory BASEPATH written by the ResearchDoom engine.
%
%   See alos: RDMGETFRAME().

% Copyright (c) 2016 Andrea Vedaldi

fid = fopen(fullfile(basePath, 'log.txt'), 'r') ;
text = fread(fid,+inf,'char=>char')' ;
fclose(fid) ;

% Get player and tics.
tokens = regexp(text, '(\d+) player:([\de.,-]+)', 'tokenExtents', 'dotexceptnewline') ;
rdb.player.tic = zeros(1,numel(tokens)) ;
rdb.player.position = zeros(3,numel(tokens)) ;
rdb.player.orientation = zeros(1,numel(tokens)) ;
for i = 1:numel(tokens)
  tk = tokens{i} ;
  rdb.player.tic(i) = sscanf(text(tk(1,1):tk(1,2)),'%d') ;
  xyza = sscanf(text(tk(2,1):tk(2,2)),'%f,%f,%f,%f') ;
  rdb.player.position(:,i) = xyza(1:3) ;
  rdb.player.orientation(i) = xyza(4) ;
end

% Get objects.
tokens = regexp(text, '(\d+) spawn:(\d+) type:(\d+) \[([\d\w]+)\]', ...
  'tokenExtents', 'dotexceptnewline') ;
rdb.basePath = basePath ;
rdb.objects.id = zeros(1, numel(tokens)) ;
rdb.objects.startTic = zeros(1, numel(tokens)) ;
rdb.objects.endTic = zeros(1, numel(tokens)) ;
rdb.objects.label = zeros(1, numel(tokens)) ;
for i = 1:numel(tokens)
  tk = tokens{i} ;
  rdb.objects.id(i) = sscanf(text(tk(2,1):tk(2,2)),'%d') ;
  rdb.objects.startTic(i) = sscanf(text(tk(1,1):tk(1,2)),'%d') ;
  rdb.objects.endTic(i) = +inf ;
  rdb.objects.label(i) = sscanf(text(tk(3,1):tk(3,2)),'%d') ;
end

tokens = regexp(text, '(\d+) remove:(\d+)', 'tokenExtents', 'dotexceptnewline') ;
for i = 1:numel(tokens)
  tk = tokens{i} ;
  s = find(rdb.objects.id == sscanf(text(tk(2,1):tk(2,2)),'%d')) ;
  rdb.objects.endTic(s) = sscanf(text(tk(1,1):tk(2,1)),'%d') ;
end

% Get levels.
tokens = regexp(text, '(\d+) level loaded: ([\d\w]+)', 'tokenExtents', 'dotexceptnewline') ;
rdb.levels.name = cell(1,numel(tokens)) ;
rdb.levels.startTic = zeros(1,numel(tokens)) ;
for i = 1:numel(tokens)
  tk = tokens{i} ;
  rdb.levels.name{i} = text(tk(2,1):tk(2,2)) ;
  rdb.levels.startTic(i) = sscanf(text(tk(1,1):tk(1,2)),'%d') ;
end
rdb.levels.endTic = [rdb.levels.startTic(2:end)-1, max(rdb.player.tic)] ;

% Get tics.
rdb.tics.id = rdb.player.tic ;
[~,rdb.tics.level] = histc(rdb.tics.id, [rdb.levels.startTic rdb.levels.endTic(end)+1]) ;

if 0
  ok = false(size(rdb.tics.id)) ;
  if exist(fullfile(basePath, 'rgb'), 'dir')
    for i = 1:numel(ok)
      ok(i) = exist(fullfile(basePath, 'rgb', sprintf('%05.png', rdb.tics.id(i)))) ;
    end
  else
    for i = 1:numel(ok)
      ok(i) = exist(...
        fullfile(basePath, sprintf('map%02d', rdb.tics.level(i)), 'rgb', sprintf('%05.png', rdb.tics.id(i))), ...
        'file') ;
    end
  end
  rdb.tics.id = rdb.tics.id(ok) ;
  rdb.tics.level = rdb.tics.level(ok) ;
end

% Get classes.
rdb.classes.name = getNames() ;
rdb.classes.label = 0:numel(rdb.classes.name)-1 ;
end

function names = getNames()
names = {...
  'PLAYER', ...
  'POSSESSED', ...
  'SHOTGUY', ...
  'VILE', ...
  'FIRE', ...
  'UNDEAD', ...
  'TRACER', ...
  'SMOKE', ...
  'FATSO', ...
  'FATSHOT', ...
  'CHAINGUY', ...
  'TROOP', ...
  'SERGEANT', ...
  'SHADOWS', ...
  'HEAD', ...
  'BRUISER', ...
  'BRUISERSHOT', ...
  'KNIGHT', ...
  'SKULL', ...
  'SPIDER', ...
  'BABY', ...
  'CYBORG', ...
  'PAIN', ...
  'WOLFSS', ...
  'KEEN', ...
  'BOSSBRAIN', ...
  'BOSSSPIT', ...
  'BOSSTARGET', ...
  'SPAWNSHOT', ...
  'SPAWNFIRE', ...
  'BARREL', ...
  'TROOPSHOT', ...
  'HEADSHOT', ...
  'ROCKET', ...
  'PLASMA', ...
  'BFG', ...
  'ARACHPLAZ', ...
  'PUFF', ...
  'BLOOD', ...
  'TFOG', ...
  'IFOG', ...
  'TELEPORTMAN', ...
  'EXTRABFG', ...
  'MISC0', ...
  'MISC1', ...
  'MISC2', ...
  'MISC3', ...
  'MISC4', ...
  'MISC5', ...
  'MISC6', ...
  'MISC7', ...
  'MISC8', ...
  'MISC9', ...
  'MISC10', ...
  'MISC11', ...
  'MISC12', ...
  'INV', ...
  'MISC13', ...
  'INS', ...
  'MISC14', ...
  'MISC15', ...
  'MISC16', ...
  'MEGA', ...
  'CLIP', ...
  'MISC17', ...
  'MISC18', ...
  'MISC19', ...
  'MISC20', ...
  'MISC21', ...
  'MISC22', ...
  'MISC23', ...
  'MISC24', ...
  'MISC25', ...
  'CHAINGUN', ...
  'MISC26', ...
  'MISC27', ...
  'MISC28', ...
  'SHOTGUN', ...
  'SUPERSHOTGUN', ...
  'MISC29', ...
  'MISC30', ...
  'MISC31', ...
  'MISC32', ...
  'MISC33', ...
  'MISC34', ...
  'MISC35', ...
  'MISC36', ...
  'MISC37', ...
  'MISC38', ...
  'MISC39', ...
  'MISC40', ...
  'MISC41', ...
  'MISC42', ...
  'MISC43', ...
  'MISC44', ...
  'MISC45', ...
  'MISC46', ...
  'MISC47', ...
  'MISC48', ...
  'MISC49', ...
  'MISC50', ...
  'MISC51', ...
  'MISC52', ...
  'MISC53', ...
  'MISC54', ...
  'MISC55', ...
  'MISC56', ...
  'MISC57', ...
  'MISC58', ...
  'MISC59', ...
  'MISC60', ...
  'MISC61', ...
  'MISC62', ...
  'MISC63', ...
  'MISC64', ...
  'MISC65', ...
  'MISC66', ...
  'MISC67', ...
  'MISC68', ...
  'MISC69', ...
  'MISC70', ...
  'MISC71', ...
  'MISC72', ...
  'MISC73', ...
  'MISC74', ...
  'MISC75', ...
  'MISC76', ...
  'MISC77', ...
  'MISC78', ...
  'MISC79', ...
  'MISC80', ...
  'MISC81', ...
  'MISC82', ...
  'MISC83', ...
  'MISC84', ...
  'MISC85', ...
  'MISC86'};
end