defaults:
  - base
  - ../wad@_global_.wad: doom2-v1.9
  - _self_

name: "doom2_13450"
url: "https://dsdarchive.com/files/demos/doom2/26819/lvall-9450.zip"
md5_archive: "38c96da4dd91a9a88ebace836194a400"
md5: "836ab0d3b81d5decbfa1d7117230004c"

